#  ____     ___ |    / _____ _____
# |  __    |    |___/    |     |
# |___| ___|    |    \ __|__   |     gsKit Open Source Project.
# ----------------------------------------------------------------------
# Copyright 2004 - Chris "Neovanglist" Gilbert <Neovanglist@LainOS.org>
# Licenced under Academic Free License version 2.0
# Review gsKit README & LICENSE files for further details.
#
# Makefile.global - Makefile global variable include.
# Only intended for compiling gsKit
#

include ~/gsKit/ee/Rules.make

EE_LIBS = -Xlinker --start-group $(EE_LIBS_EXTRA)


ifdef GSKIT_DEBUG
    EE_CFLAGS += -DGSKIT_DEBUG
    EE_INCS += -I$(PS2GDB)/ee
    EE_LIB_DIRS += -L$(PS2GDB)/lib
endif

# include dir
EE_INCS += -I$(GSKITSRC)/ee/gs/include -I$(GSKITSRC)/ee/dma/include


# linker flags
EE_LIB_DIRS += -L$(PS2SDK)/ee/lib
EE_LDFLAGS += $(EE_LIB_DIRS)
EE_LIB_DIRS += -L./libs/

EE_LIBS += -lgskit_toolkit
EE_LIBS += -lgskit -ldmakit
EE_LIBS += -ldebug -lc -ldraw -lgraph -lmath3d -lpacket2 -ldma -lpacket -lpatches -lpad -lfont

EE_CXXFLAGS +=                \
	-std=c++11                  \
	-O3                       \
	-funroll-loops            \
	-fexpensive-optimizations \
	-fno-exceptions           \
	-fno-rtti                 \
	-Wall                     \
	-Wformat=2                \
	-Wmissing-braces          \
	-Wparentheses             \
	-Wpointer-arith           \
	-Wreturn-type             \
	-Wsequence-point          \
	-Wswitch                  \
	-Wuninitialized           \
	-Wunknown-pragmas         \
	-Wwrite-strings           \
	$(GLOBAL_DEFINES)

all: $(EE_BIN)

clean:
	rm -f $(EE_OBJS) $(EE_BIN) $(EE_ISO)

install: all